### PR TITLE
HtmlHandler and added to ContentType

### PR DESCRIPTION
**Pull request by t-keazirian**
* Updated `ContentType` to include `text/html`
* Added route for `/html_response`
* Added `HtmlHandler`

### CODE REVIEW

**Comment by Aoxian** [comment]
This looks good.  Have you tested with a more flushed out HTML response? It may be worth it to make a little page and post the screenshots on this PR.

**Comment by t-keazirian** [comment]
> This looks good. Have you tested with a more flushed out HTML response? It may be worth it to make a little page and post the screenshots on this PR.

I was wondering about testing this, in terms of unit testing, not just with the acceptance tests.  Do you think a `MockHtmlHandler` would work here?  But I don't know how I would use it differently than the other MockHandler...I'm not sure how I would then make a page and see that?... I'm definitely racking my brain trying to think about the best ways to test this.

**Comment by t-keazirian** [comment]
> > This looks good. Have you tested with a more flushed out HTML response? It may be worth it to make a little page and post the screenshots on this PR.
> 
> I was wondering about testing this, in terms of unit testing, not just with the acceptance tests. Do you think a `MockHtmlHandler` would work here? But I don't know how I would use it differently than the other MockHandler...I'm not sure how I would then make a page and see that?... I'm definitely racking my brain trying to think about the best ways to test this.


This isn't "testing" per say but this is what I get when I make a Postman request:

Screen Shot 2022-07-18 at 2 40 16 PM

**Comment by t-keazirian** [comment]
> > > This looks good. Have you tested with a more flushed out HTML response? It may be worth it to make a little page and post the screenshots on this PR.
> > 
> > 
> > I was wondering about testing this, in terms of unit testing, not just with the acceptance tests. Do you think a `MockHtmlHandler` would work here? But I don't know how I would use it differently than the other MockHandler...I'm not sure how I would then make a page and see that?... I'm definitely racking my brain trying to think about the best ways to test this.
> 
> This isn't "testing" per say but this is what I get when I make a Postman request:
> 
> Screen Shot 2022-07-18 at 2 40 16 PM

And if I change the `body` to this (in `HtmlHandler`):
```csharp
        string body = "<!doctype html>" +
                      "<html>" +
                      "<head>" +
                      "<title>This is the title of the webpage!</title>" +
                      "</head>" +
                      "<body>" +
                      "<p>This is an example paragraph. Anything in the <strong>body</strong> tag will appear on the page, just like this <strong>p</strong> tag and its contents.</p>" +
                      "</body>" +
                      "</html>";
```

It still formats correctly and looks good:
Screen Shot 2022-07-18 at 2 43 52 PM

** I originally thought I would have to add `\r\n` after every tag but it seems I don't have to!?

**Comment by Aoxian** [comment]
cool! though I kinda meant opening it in a web-browser (as opposed to postman)

**Comment by Aoxian** [comment]
Any other tests you want to add are fine; I was thinking it would just be cool to make sure that the html file you create, could be open in a browser.  Just a manual test for fun really.

**Comment by t-keazirian** [comment]
> Any other tests you want to add are fine; I was thinking it would just be cool to make sure that the html file you create, could be open in a browser. Just a manual test for fun really.

Here it is in the browser!  It is very cool!

Screen Shot 2022-07-18 at 4 54 10 PM

**Pull request merged**
